name: Build my QMK configuration

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build-qmk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: crkbd/rev1
          keymap: default
          controller: helios
          local-keymap-path: corne/keymaps/default

      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: qmk-output